apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - mountPath: /var/log/nginx
        name: storage1
  volumes:
    - name: storage1
      persistentVolumeClaim:
        claimName: claim-log-1
      